name: Self-Hosted Runner Example

on:
  workflow_dispatch:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string

        
  workflow_call:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string


jobs:
  Test-E2E:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Prepare APK or APP
      env: 
        build_url: ${{inputs.build_url}}
        OS: ${{inputs.OS}}
      id: prepare_app
      run: |
        if [ ${{inputs.OS}} == 'Android' ] 
        then export extension=apk
        else export extension=ipa
        fi
        curl ${{inputs.build_url}} -o app.$extension
        echo "result=$(curl -u "${{secrets.BS_USER}}:${{secrets.bs_KEY}}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
          -F "file=@./app.$extension"| | grep -o '"app_url":"[^"]*' | sed 's/"app_url":"//')" >> $GITHUB_OUTPUT



    - name: Run a simple test
      env: 
        build_url: ${{ steps.prepare_app.outputs.result }}
        OS: ${{inputs.OS}}
      run: |
        npm ci
        npm run test:bs:${{inputs.OS}}
