name: Run E2E tests in BS
run-name: Run ${{inputs.OS}} E2E tests in BS
on:
  workflow_dispatch:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string
      Branch:
        description: APP Branch
        required: true
        type: string
        
  workflow_call:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string
      Branch:
        description: APP Branch
        required: true
        type: string
  

jobs:
  Test-E2E:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple test
      shell: bash
      env: 
        OS: ${{inputs.OS}}
        APK_URL: ${{inputs.build_url}}
        APP_URL: ${{inputs.build_url}}
        BROWSERSTACK_USERNAME: ${{secrets.BS_USER}}
        BROWSERSTACK_ACCESS_KEY: ${{secrets.bs_KEY}}
        MOCK_SERVER_USERNAME: ${{secrets.MOCK_SERVER_USERNAME}}
        MOCK_SERVER_PASSWORD: ${{secrets.MOCK_SERVER_PASSWORD}}



      run: |
        npm i
        npm run test:bsp:${{inputs.OS}}

    - name: Clean up
      if: always()
      run: |
        rm .env