name: Self-Hosted Runner Example

on:
  workflow_dispatch:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string

        
  workflow_call:
    inputs:
      build_url:
        description: OTA URL
        required: true
        type: string
      OS:
        description: OS
        required: true
        type: string


jobs:
  Test-E2E:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Prepare APK or APP
      env: 
        build_url: ${{inputs.build_url}}
        OS: ${{inputs.OS}}
      id: prepare_app
      run: |
        if [ "${{inputs.OS}}" == "android" ] 
        then url="$(echo ${{inputs.build_url}} | sed 's/https:\/\/otashare.mobgen.com\/build\//https:\/\/otashare.mobgen.com\/build\/download\//'| sed 's/\/esmorga-qa//' )"
        else url="$(echo ${{inputs.build_url}} | sed 's/https:\/\/otashare.mobgen.com\/build\//https:\/\/otashare.mobgen.com\/build\/download\//'| sed 's/\/esmorga-qa//' )"
        fi

        
        result=$(curl -u "${{secrets.BS_USER}}:${{secrets.bs_KEY}}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "url=$url"| grep -o '"app_url":"[^"]*' | sed 's/"app_url":"//')"
        if [ "$result" == "" ]
        then
        exit 1
        fi
        echo "result=$result">> $GITHUB_OUTPUT



    - name: Run a simple test
      env: 
        OS: ${{inputs.OS}}
        BROWSERSTACK_APP_ID: ${{ steps.prepare_app.outputs.result }}
        BROWSERSTACK_USERNAME: ${{secrets.BS_USER}}
        BROWSERSTACK_ACCESS_KEY: ${{secrets.bs_KEY}}

      run: |
        npm i
        npm run test:bs:${{inputs.OS}}
